name: 'setup-yc-cli'
description: 'Setup Yandex Cloud CLI'
author: 'T0R0NT0T0KY0'
branding:
  icon: 'alert-triangle'
  color: 'purple'
inputs:
  SA_KEY:
    description: 'Yandex cloud service account private key. No logging in if parameter is not provided.'
    required: false
    default: ''
  FOLDER_ID:
    description: 'Yandex cloud service account folder id.'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Get latest yc version number
      shell: bash
      id: version
      run: |
        version=$(curl -s --fail https://storage.yandexcloud.net/yandexcloud-yc/release/stable)
        echo "version=$version" >> $GITHUB_OUTPUT

    - name: Cache yc binary
      uses: actions/cache@v4
      id: cache-yc-cli
      with:
        path: /usr/local/bin/yc
        key: yc-cli-${{ steps.version.outputs.version }}

    - name: Get yc binary if cache miss
      if: steps.cache-yc-cli.outputs.cache-hit != 'true'
      shell: bash
      run: |
        tmp="$(mktemp)"
        
        echo "Downloading yc cli version ${{ steps.version.outputs.version }}"
        sudo curl --fail "https://storage.yandexcloud.net/yandexcloud-yc/release/${{ steps.version.outputs.version }}/linux/amd64/yc" -o "$tmp"
        sudo install -m 755 "$tmp" /usr/local/bin/yc
        rm -f "$tmp"

    - name: Set permissions for yc cli binary
      shell: bash
      run: |
        sudo chmod a+rx /usr/local/bin/yc

    - name: Authorize service account
      if: ${{ inputs.SA_KEY != '' }}
      shell: bash
      run: |
        yc config set service-account-key <(echo '${{ inputs.SA_KEY }}')

    - name: Set folder id
      if: ${{ inputs.FOLDER_ID != '' }}
      shell: bash
      run: |
        yc config set folder-id ${{ inputs.FOLDER_ID }}
